title: <p align="center"> Kunal Mahale </p>
logo: /assets/img/KunalMahale.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/kunalmahale449/">LinkedIn</a> |
  <a href="https://github.com/kunal449">GitHub</a>
  
  <br>   
  I'm working on Big Data, Spark, Dta Intensive platforms.
  <br>
  </p>



theme: jekyll-theme-minimal